# Generated by Django 5.2.6 on 2025-09-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makpost', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
