# Generated by Django 5.2.7 on 2025-10-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makpost', '0004_remove_customuser_username_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
